[RunControl]
config_log_path = logs/
EUDAQ_CTRL_PRODUCER_LAST_START = DryXDCProducer
EUDAQ_CTRL_PRODUCER_FIRST_STOP = DryXDCProducer

[Producer.DryXDCProducer]
EUDAQ_DC = HidraDataCollector
DATA_IN_PATH = /home/rscaglio/work/eudaq_hidra/user/hidra/run/data/RawData-2025.09.04-06.57.38.run632.txt

[DataCollector.HidraDataCollector]
# connection to the monitor
EUDAQ_MN = my_mon
EUDAQ_FW = native
EUDAQ_FW_PATTERN = out_data/run$3R_$12D$X
EUDAQ_DATACOL_SEND_MONITOR_FRACTION = 10
# config-parameters of the example data collector
EX0_MAX_EVENTS = 100000

[Producer.my_pd0]
EUDAQ_DQ = my_dc
DATA_IN_PATH = /home/nicolo/Downloads/Run632.0_list.dat
REPLAY_EVENT_SPACING_MS = 0

