
[RunControl]
EUDAQ_CTRL_PRODUCER_LAST_START = HidraDryXDCProducer
EUDAQ_CTRL_PRODUCER_FIRST_STOP = HidraDryXDCProducer



[Producer.DryXDCProducer]
EUDAQ_DQ = my_dc
DATA_IN_PATH = /home/rscaglio/work/eudaq_hidra/user/hidra/run/data/RawData-2025.09.04-06.57.38.run632.txt
